version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: Canteen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage
    ports:
      - "5432:5432"
    networks:
      - my-network

  backend:
    image: crimsonowl/neuro-canteen-backend:latest
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Canteen
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8142:8142"
    networks:
      - my-network

  frontend:
    image: crimsonowl/neuro-canteen-frontend:latest
    restart: always
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge